staging 1

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -150,6 +150,15 @@ jobs:
         run: |
           echo "Subnet IDs recibidos: ${{ secrets.SUBNET_IDS }}"
 
+          
+      - name: Check if SUBNET_IDS is empty
+        run: |
+          if [ -z "${{ secrets.SUBNET_IDS }}" ]; then
+            echo "❌ ERROR: El valor de SUBNET_IDS está vacío."
+            exit 1
+          else
+            echo "✅ SUBNET_IDS tiene contenido (aunque no se muestra por seguridad)."
+          fi
       # 3. Desplegar/Actualizar el stack CloudFormation de Staging
       - name: Deploy CloudFormation Staging Stack
         run: |
